### ISSUE TITLE
Cannot dynamically link to system libzstd when building wheel

### ISSUE THREAD

**Issue by bnavigator** [animalize/pyzstd#18]
I want to build a wheel for openSUSE Tumbleweed linking the system libzstd.

The PEP517 setuptools/wheel legacy backend does not recognized the `--dynamic-link-zstd` flag, provided by `--build-option`

```
[    2s] + /usr/bin/python3.8 -mpip wheel --verbose --progress-bar off --disable-pip-version-check --use-pep517 --no-build-isolation --no-deps --wheel-dir ./build --build-option=--dynamic-link-zstd .
[    2s] WARNING: Implying --no-binary=:all: due to the presence of --build-option / --global-option / --install-option. Consider using --config-settings for more flexibility.
[    2s] DEPRECATION: --no-binary currently disables reading from the cache of locally built wheels. In the future --no-binary will not influence the wheel cache. pip 23.1 will enforce this behaviour change. A possible replacement is to use the --no-cache-dir option. You can use the flag --use-feature=no-binary-enable-wheel-cache to test the upcoming behaviour. Discussion can be found at https://github.com/pypa/pip/issues/11453
[    2s] Processing /home/abuild/rpmbuild/BUILD/pyzstd-0.15.3
[    2s]   Preparing metadata (pyproject.toml): started
[    2s]   Running command Preparing metadata (pyproject.toml)
[    2s]   running dist_info
[    2s]   creating /tmp/pip-modern-metadata-7nddtet7/pyzstd.egg-info
[    2s]   writing /tmp/pip-modern-metadata-7nddtet7/pyzstd.egg-info/PKG-INFO
[    2s]   writing dependency_links to /tmp/pip-modern-metadata-7nddtet7/pyzstd.egg-info/dependency_links.txt
[    2s]   writing top-level names to /tmp/pip-modern-metadata-7nddtet7/pyzstd.egg-info/top_level.txt
[    2s]   writing manifest file '/tmp/pip-modern-metadata-7nddtet7/pyzstd.egg-info/SOURCES.txt'
[    2s]   reading manifest file '/tmp/pip-modern-metadata-7nddtet7/pyzstd.egg-info/SOURCES.txt'
[    2s]   reading manifest template 'MANIFEST.in'
[    2s]   warning: no previously-included files matching '__pycache__' found under directory '*'
[    2s]   warning: no previously-included files matching '*.pyc' found under directory '*'
[    2s]   adding license file 'LICENSE'
[    2s]   writing manifest file '/tmp/pip-modern-metadata-7nddtet7/pyzstd.egg-info/SOURCES.txt'
[    2s]   creating '/tmp/pip-modern-metadata-7nddtet7/pyzstd-0.15.3.dist-info'
[    2s]   Preparing metadata (pyproject.toml): finished with status 'done'
[    2s] Building wheels for collected packages: pyzstd
[    2s]   WARNING: Ignoring --build-option when building pyzstd using PEP 517
[    2s]   Building wheel for pyzstd (pyproject.toml): started
[    2s]   Running command Building wheel for pyzstd (pyproject.toml)
[    2s]   running bdist_wheel
[    2s]   running build
[    2s]   running build_py
[    2s]   creating build/lib.linux-x86_64-cpython-38
[    2s]   creating build/lib.linux-x86_64-cpython-38/pyzstd
[    2s]   copying src/__init__.py -> build/lib.linux-x86_64-cpython-38/pyzstd
[    2s]   creating build/lib.linux-x86_64-cpython-38/pyzstd/c
[    2s]   copying src/c/c_pyzstd.py -> build/lib.linux-x86_64-cpython-38/pyzstd/c
[    2s]   copying src/__init__.pyi -> build/lib.linux-x86_64-cpython-38/pyzstd
[    2s]   copying src/py.typed -> build/lib.linux-x86_64-cpython-38/pyzstd
[    2s]   running build_ext
[    2s]   building 'pyzstd.c._zstd' extension
[    2s]   creating build/temp.linux-x86_64-cpython-38
[    2s]   creating build/temp.linux-x86_64-cpython-38/src
[    2s]   creating build/temp.linux-x86_64-cpython-38/src/bin_ext
[    2s]   creating build/temp.linux-x86_64-cpython-38/zstd
[    2s]   creating build/temp.linux-x86_64-cpython-38/zstd/lib
[    2s]   creating build/temp.linux-x86_64-cpython-38/zstd/lib/common
[    2s]   creating build/temp.linux-x86_64-cpython-38/zstd/lib/compress
[    2s]   creating build/temp.linux-x86_64-cpython-38/zstd/lib/decompress
[    2s]   creating build/temp.linux-x86_64-cpython-38/zstd/lib/dictBuilder
[    2s]   gcc -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -g -DOPENSSL_LOAD_CONF -fwrapv -fno-semantic-interposition -O2 -Wall -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -g -O2 -Wall -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -g -O2 -Wall -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -g -fPIC -DZSTD_MULTITHREAD -Izstd/lib -Izstd/lib/dictBuilder -I/usr/include/python3.8 -c src/bin_ext/_zstdmodule.c -o build/temp.linux-x86_64-cpython-38/src/bin_ext/_zstdmodule.o -g0
[    3s]   gcc -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -g -DOPENSSL_LOAD_CONF -fwrapv -fno-semantic-interposition -O2 -Wall -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -g -O2 -Wall -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -g -O2 -Wall -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -g -fPIC -DZSTD_MULTITHREAD -Izstd/lib -Izstd/lib/dictBuilder -I/usr/include/python3.8 -c zstd/lib/common/debug.c -o build/temp.linux-x86_64-cpython-38/zstd/lib/common/debug.o -g0
...
```

When I delete the zstd source directory:
```
[    2s] + rm -r zstd
[    2s] + RPM_EC=0
[    2s] ++ jobs -p
[    2s] + exit 0
[    2s] Executing(%build): /usr/bin/bash -e /var/tmp/rpm-tmp.oZ4bkY
[    2s] + umask 022
[    2s] + cd /home/abuild/rpmbuild/BUILD
[    2s] + /usr/bin/rm -rf /home/abuild/rpmbuild/BUILDROOT/python-pyzstd-0.15.3-0.x86_64
[    2s] ++ dirname /home/abuild/rpmbuild/BUILDROOT/python-pyzstd-0.15.3-0.x86_64
[    2s] + /usr/bin/mkdir -p /home/abuild/rpmbuild/BUILDROOT
[    2s] + /usr/bin/mkdir /home/abuild/rpmbuild/BUILDROOT/python-pyzstd-0.15.3-0.x86_64
[    2s] + cd pyzstd-0.15.3
[    2s] ++ '[' -f _current_flavor ']'
[    2s] ++ true
[    2s] + last_flavor=
[    2s] + '[' -z '' ']'
[    2s] + last_flavor=tmp
[    2s] + '[' tmp '!=' python38 ']'
[    2s] + '[' -d build ']'
[    2s] + '[' -d _build.python38 ']'
[    2s] + echo python38
[    2s] + python_flavor=python38
[    2s] + myargs='--build-option=--dynamic-link-zstd .'
[    2s] + '[' -f './dist/*-none-any.whl' ']'
[    2s] + /usr/bin/python3.8 -mpip wheel --verbose --progress-bar off --disable-pip-version-check --use-pep517 --no-build-isolation --no-deps --wheel-dir ./build --build-option=--dynamic-link-zstd .
[    2s] WARNING: Implying --no-binary=:all: due to the presence of --build-option / --global-option / --install-option. Consider using --config-settings for more flexibility.
[    2s] DEPRECATION: --no-binary currently disables reading from the cache of locally built wheels. In the future --no-binary will not influence the wheel cache. pip 23.1 will enforce this behaviour change. A possible replacement is to use the --no-cache-dir option. You can use the flag --use-feature=no-binary-enable-wheel-cache to test the upcoming behaviour. Discussion can be found at https://github.com/pypa/pip/issues/11453
[    2s] Processing /home/abuild/rpmbuild/BUILD/pyzstd-0.15.3
[    2s]   Preparing metadata (pyproject.toml): started
[    2s]   Running command Preparing metadata (pyproject.toml)
[    2s]   Traceback (most recent call last):
[    2s]     File "/usr/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
[    2s]       main()
[    2s]     File "/usr/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
[    2s]       json_out['return_val'] = hook(**hook_input['kwargs'])
[    2s]     File "/usr/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
[    2s]       return hook(metadata_directory, config_settings)
[    2s]     File "/usr/lib/python3.8/site-packages/setuptools/build_meta.py", line 377, in prepare_metadata_for_build_wheel
[    2s]       self.run_setup()
[    2s]     File "/usr/lib/python3.8/site-packages/setuptools/build_meta.py", line 484, in run_setup
[    2s]       super(_BuildMetaLegacyBackend,
[    2s]     File "/usr/lib/python3.8/site-packages/setuptools/build_meta.py", line 335, in run_setup
[    2s]       exec(code, locals())
[    2s]     File "<string>", line 67, in <module>
[    2s]     File "<string>", line 31, in get_zstd_files_list
[    2s]   FileNotFoundError: [Errno 2] No such file or directory: 'zstd/lib/common/'
[    2s]   error: subprocess-exited-with-error
[    2s]   
[    2s]   × Preparing metadata (pyproject.toml) did not run successfully.
[    2s]   │ exit code: 1
[    2s]   ╰─> See above for output.
[    2s]   
[    2s]   note: This error originates from a subprocess, and is likely not a problem with pip.
[    2s]   full command: /usr/bin/python3.8 /usr/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpbkbuz7zh
[    2s]   cwd: /home/abuild/rpmbuild/BUILD/pyzstd-0.15.3
[    2s]   Preparing metadata (pyproject.toml): finished with status 'error'
[    2s] error: metadata-generation-failed
[    2s] 
[    2s] × Encountered error while generating package metadata.
[    2s] ╰─> See above for output.
[    2s] 
[    2s] note: This is an issue with the package mentioned above, not pip.
[    2s] hint: See above for details.
[    2s] error: Bad exit status from /var/tmp/rpm-tmp.oZ4bkY (%build)
```

**Comment by animalize** [comment]
There should be double quotes:
```sh
# build and install
sudo pip3 install --install-option="--dynamic-link-zstd" -v pyzstd-0.14.4.tar.gz
# build a redistributable wheel
pip3 wheel --build-option="--dynamic-link-zstd" -v pyzstd-0.14.4.tar.gz
```
If it still fails, install packages like `zstd-dev` and `zstd1-dev`.

**Comment by bnavigator** [comment]
the double quotes are parsed by the shell and not passed to the python interpreter

**Comment by bnavigator** [comment]
BTW:

```
export PIP_BUILD_OPTION="--dynamic-link-zstd"
```

or `export PIP_CONFIG_FILE=pipconfig` and

```toml
[wheel]
build-option = --dynamic-link-zstd
```

shows the same

**Comment by animalize** [comment]
I'm investigating the problem.
I will go to bed soon, I may have time to do it tomorrow, please use the workaround at present.

**Comment by animalize** [comment]
If change `--use-pep517` to `--no-use-pep517`, the `--dynamic-link-zstd` argument can be recognized.
It's OK without double quotes.
```sh
python3 -m pip wheel --verbose --progress-bar off --disable-pip-version-check --no-use-pep517 --no-build-isolation --no-deps --wheel-dir ./build --build-option=--dynamic-link-zstd .
```
Tested on Ubuntu 22.04.

Maybe `pyproject.toml` will be supported in future versions.

**Comment by animalize** [comment]
Quoted from PEP 517:

> If the pyproject.toml file is absent, or the build-backend key is missing, the source tree is not using this specification, and tools **should** revert to the legacy behaviour of running setup.py (either directly, or by implicitly invoking the setuptools.build_meta:\_\_legacy\_\_ backend).
> 
> Where the build-backend key exists, this takes precedence and the source tree follows the format and conventions of the specified backend (as such no setup.py is needed unless the backend requires it). Projects may still wish to include a setup.py for compatibility with tools that do not use this spec.

No plan to support PEP 517, `setup.py` is fine.

**Comment by animalize** [comment]
I add two build example in doc: https://github.com/animalize/pyzstd/commit/6ff501f4cca5420436dbda8f44b4974d1297068b

**Comment by animalize** [comment]
Now PEP 517 is supported: https://github.com/animalize/pyzstd/commit/a818c5d4c6926b74f72a69a6971ada3bf5d9bbbf
Thanks for pushing this step, please try.

**Comment by animalize** [comment]
`pip` raises an warning when using your command line.
```sh
WARNING: Ignoring --build-option when building pyzstd using PEP 517
```
So `--dynamic-link-zstd` is still being ignored.
`pip` is tring to suppoprt `--config-settings`, but the [PR](https://github.com/pypa/pip/pull/11634) has not been merged.

Please use [`build`](https://pypi.org/project/build/) module, and follow the examples in doc.

**Comment by animalize** [comment]
`build` module doesn't support build from `sdist` file yet: https://github.com/pypa/build/issues/311. If unzip first, may package unnecessary files.
`pip` module doesn't support `--config-setting` yet: https://github.com/pypa/pip/issues/11325

So I remove the examples in doc.

If you use `build` module, clear the directory first:
```sh
  # build a redistributable wheel using `build` module
  rm -rf pyzstd-0.15.4
  python3 -m tarfile -e pyzstd-0.15.4.tar.gz
  python3 -m build --wheel -C="--build-option=--dynamic-link-zstd" pyzstd-0.15.4

  # Using `build` module with more than one option
  rm -rf pyzstd-0.15.4
  python3 -m tarfile -e pyzstd-0.15.4.tar.gz
  python3 -m build --wheel -C="--build-option=--dynamic-link-zstd" -C="--build-option=--cffi" pyzstd-0.15.4
```

**Comment by animalize** [comment]
`pip` already supports `--config-settings`, examples are upadted:
https://pyzstd.readthedocs.io/en/latest/#build-pyzstd-module-with-options

**Comment by animalize** [comment]
pyzstd 0.15.4 released.
